require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'

$FirebaseSDKVersion = '7.0.0'

target 'rn_starter_kit' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
  
  target 'rn_starter_kitTests' do
    inherit! :complete
    # Pods for testing
  end


  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper-Folly' => '2.3.0' })
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'rn_starter_kit-tvOS' do
  # Pods for rn_starter_kit-tvOS

  target 'rn_starter_kit-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
